### ISSUE TITLE
latest source?

### ISSUE THREAD

**Issue by KamarajuKusumanchi** [zyga/command-not-found#7]
According to http://archive.ubuntu.com/ubuntu/pool/main/c/command-not-found/?C=M;O=D , the latest release http://archive.ubuntu.com/ubuntu/pool/main/c/command-not-found/command-not-found_18.04.5.tar.gz was done on "2018-05-14 18:43" . However, the last commit on this repository is on  2013-06-17 <https://github.com/zyga/command-not-found/commits/master> . Could you please update this repository to the latest source code?

**Comment by zyga** [comment]
I'm not actively maintaining command-not-found anymore.
